// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnOM0wojd9kdADn5QVdTM0QPXMqVIDnSY',
    appId: '1:459968840143:web:4444fc93ec960c6a4012ba',
    messagingSenderId: '459968840143',
    projectId: 'fir-demo-5e338',
    authDomain: 'fir-demo-5e338.firebaseapp.com',
    storageBucket: 'fir-demo-5e338.firebasestorage.app',
    measurementId: 'G-0PGJB932WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO71silkAMEwUCrC3plBQ20WkLh52S-J0',
    appId: '1:459968840143:android:2780b3168d1a60474012ba',
    messagingSenderId: '459968840143',
    projectId: 'fir-demo-5e338',
    storageBucket: 'fir-demo-5e338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAx5S6lniTUqsB3FL3RG3NcErcKO1s6Og',
    appId: '1:459968840143:ios:32960a137c62f9a04012ba',
    messagingSenderId: '459968840143',
    projectId: 'fir-demo-5e338',
    storageBucket: 'fir-demo-5e338.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAx5S6lniTUqsB3FL3RG3NcErcKO1s6Og',
    appId: '1:459968840143:ios:32960a137c62f9a04012ba',
    messagingSenderId: '459968840143',
    projectId: 'fir-demo-5e338',
    storageBucket: 'fir-demo-5e338.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
